name: "Create Pull Request"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create PR from'
        required: true
        default: 'feature/ignore-weekend-check'
      base:
        description: 'Base branch to merge into'
        required: true
        default: 'master'
      title:
        description: 'PR title'
        required: true
        default: 'Добавлена возможность принудительной проверки без учета выходных дней'
      body:
        description: 'PR description'
        required: true
        default: 'Добавлен параметр force_check для игнорирования проверки на выходной день и минимальный лончер launcher_test_force.py'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Создан PR для слияния ${{ github.event.inputs.branch }} в ${{ github.event.inputs.base }}"
        title: ${{ github.event.inputs.title }}
        body: ${{ github.event.inputs.body }}
        branch: ${{ github.event.inputs.branch }}
        base: ${{ github.event.inputs.base }}
        draft: false
