name: "Run Force Test on Server"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        required: true
        default: 'feature/ignore-weekend-check'

jobs:
  run-test-force:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
      
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
    - name: Deploy script to server
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa run_test_force.py ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/watchdog/
      
    - name: Run test script on server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/watchdog && mkdir -p logs && python3 run_test_force.py > logs/run_test_force.log 2>&1"
      
    - name: Get logs
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/watchdog && cat logs/run_test_force.log"
